version: "3"
services:
  search-trace-server:
    image: danbai225/search-trace-server:latest
    container_name: search-trace-server
    restart: always
    volumes:
      - ./conf.json:/app/conf.json
      - ./logs/:/app/logs
    ports:
      - "49492:49492"